// Generates src/rpage.js from rpage-source.html — the APPROVED confirm-page
// design (Downloads/randevu-onay-sayfasi_2.html, 29 Aug 2026). The design is
// kept byte-for-byte except: the four data slots become tokens, the body tag
// gains a state class, a "cannot show details" variant is added, and the stub
// answer() becomes the real one-shot POST. Re-run after any design update:
//   node make-rpage.mjs
import fs from 'node:fs';

let html = fs.readFileSync(new URL('./rpage-source.html', import.meta.url), 'utf8');
const must = (from, to, what) => {
  if (!html.includes(from)) { console.error('✗ anchor not found: ' + what); process.exit(1); }
  html = html.replace(from, to);
};

// State class on the body: "" | "answered" | "na" (details unavailable).
must('<body>', '<body class="{{BODY}}">', 'body tag');

// The headline follows the day: Bugün / Yarın / plain.
must('<h1>Yarın sizi bekliyoruz</h1>', '<h1>{{HEADLINE}}</h1>', 'headline');

// The three data rows. Konum stays as designed.
must('<dd>22 Ağustos Cuma</dd>', '<dd>{{DATE}}</dd>', 'date row');
must('<dd><b>14:00</b></dd>', '<dd><b>{{TIME}}</b></dd>', 'time row');
must('<dd>Manikür</dd>', '<dd>{{SVC}}</dd>', 'service row');

// Thank-you texts are set server-side for the pre-answered state and
// client-side after a tap; tokens carry the initial values.
must('<h2 id="doneT">Teşekkür ederiz</h2>', '<h2 id="doneT">{{DONE_T}}</h2>', 'done title');
must('<p id="doneP">Randevunuz onaylandı.<br>Your appointment is confirmed.</p>',
     '<p id="doneP">{{DONE_P}}</p>', 'done text');

// The "details unavailable" variant: the rows and the question hide, this
// message shows. Same card, same tone, phone number one tap away below it.
must('</style>',
`  body.na .ask,body.na .btn,body.na dl{display:none}
  .na-msg{display:none;text-align:center;padding:6px 0 2px;font-size:.92rem;line-height:1.7;color:var(--ink)}
  .na-msg span{display:block;font-size:.79rem;color:var(--muted);margin-top:4px}
  body.na .na-msg{display:block}
  .err{display:none;text-align:center;margin-top:14px;font-size:.8rem;line-height:1.6;color:var(--muted)}
  .err.on{display:block}
</style>`, 'na css');
must('<p class="ask">',
`<p class="na-msg">Randevu bilgilerinize şu anda ulaşamıyoruz.
      Lütfen bizi arayın — memnuniyetle yardımcı olalım.
      <span>We cannot show your appointment details right now. Please call us — we are happy to help.</span></p>
    <p class="ask">`, 'na message');

// A failed answer POST must never look like success and never like an error
// page: a quiet line under the buttons, buttons live again.
must('    <div class="done" id="done">',
`    <p class="err" id="err">Yanıtınızı kaydedemedik — lütfen tekrar deneyin ya da bizi arayın.<br>We could not record your answer — please try again or call us.</p>
    <div class="done" id="done">`, 'error line');

// The stub becomes the real thing: one-shot POST to /r/a, double-tap guarded,
// and the page believes the SERVER's answer (a second device may have
// answered first) rather than the tapped button.
const script = `<script>
  var ID=(location.pathname.match(/\\/r\\/(\\d{6,20})/)||[])[1]||'';
  var busy=false;
  function swapDone(st){
    var t=document.getElementById('doneT'), p=document.getElementById('doneP');
    if(st==='change'){
      t.textContent='Aldık, teşekkürler';
      p.innerHTML='Sizi en kısa sürede arayıp yeni bir saat ayarlayacağız.<br>We will call you shortly to arrange a new time.';
    } else {
      t.textContent='Teşekkür ederiz';
      p.innerHTML='Randevunuz onaylandı.<br>Your appointment is confirmed.';
    }
    document.body.classList.add('answered');
    window.scrollTo({top:0,behavior:'smooth'});
  }
  function answer(kind){
    if(busy||!ID) return; busy=true;
    document.getElementById('err').classList.remove('on');
    var a=(kind==='yes')?'confirm':'change';
    fetch('/r/a',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({id:ID,a:a})})
      .then(function(r){return r.json();})
      .then(function(j){
        if(j&&j.ok){ swapDone(j.st||a); }
        else { busy=false; document.getElementById('err').classList.add('on'); }
      })
      .catch(function(){ busy=false; document.getElementById('err').classList.add('on'); });
  }
</script>`;
{
  const i0 = html.indexOf('<script>');
  const i1 = html.indexOf('</script>', i0);
  if (i0 < 0 || i1 < 0) { console.error('✗ script block not found'); process.exit(1); }
  html = html.slice(0, i0) + script + html.slice(i1 + '</script>'.length);
}

fs.writeFileSync(new URL('./src/rpage.js', import.meta.url),
  '// GENERATED by make-rpage.mjs from rpage-source.html — do not edit by hand.\n' +
  'export const R_PAGE = ' + JSON.stringify(html) + ';\n');
console.log('✓ src/rpage.js written,', html.length, 'chars');
